### ISSUE TITLE
Make auto-select default suggestion an option?

### ISSUE THREAD

**Issue by ProLoser** [ProLoser/Github-Omnibox#6]
I realize that @rodyhaddad and I have differing opinions, and it appears you may have changed it back in the recent version. It occurred to me that this may very well be a good thing to make optional so that users can control this themselves.

Perhaps we should add an option to the options page that lets you automatically use the first suggestion or not?

**Comment by rodyhaddad** [comment]
Yap, I'm not against having it optional.
If some people would prefer to not have the auto-select enabled, then I don't see any problem in adding that feature to the option page.

Though I think that having the auto-select be enabled by default is better UX.
Because typing `my notific`, I'd prefer getting redirected to my notifications page, instead of getting search results for `my notific`.
I mean, who would want to search for `my notific` really :P
