### ISSUE TITLE
Extension is no longer available on Chrome Webstore

### ISSUE THREAD

**Issue by allemangD** [ProLoser/Github-Omnibox#65]
The extension is not available on the webstore anymore, and the link in the repository description is dead. http://goo.gl/n5HJw

Workaround:

It is possible to clone the extension repository and install as an unpacked extension. 

- Navigate to chrome://extensions/
- Enable Developer Mode (toggle switch in top-right corner)
- Choose "Load Unpacked" (button in top-left corner)
- Select the Github-Omnibox repository directory

**Comment by ProLoser** [comment]
@allemangD I unpublished it because I have not been actively working on it anymore and I am frequently getting notified by Github that I'm using a deprecated authentication method.

Honestly I would kinda redo the extension a bit, more focused on my atomic searching I started building out that would rely more on observing usage patterns and suggesting relevant results and less focused on having you as a user have to memorize assorted key characters to get the desired behavior (except where it's intuitive such as `@proloser` or `@proloser/github-omnibox`.

You CAN install the extension as unpacked, but I think you're essentially using my auth credentials. If you're interested in taking over this project I am happy to assist anyone interested in doing so.

**Comment by allemangD** [comment]
Thanks for the explanation. I was unsure if perhaps the removal was unintentional, but it's good to know it wasn't.

I'm not sure if I'm in a position to take over the project, but I'll plan to look into it and see how feasible it might be for me.

Do you have any suggestions for tools or workflow when dealing with extension development? The main blocker for me is limited experience, and I'm not quite sure where to begin.

At the very least, I can create my own credentials and load the extension unpacked, so that I won't be using yours.

**Comment by ProLoser** [comment]
It is extremely easy to do because it's just JavaScript. Unfortunately this code is a bit messy so I'd almost start over from scratch with some of the same concepts carried over. I would look up chrome extension tutorials for the omnibox.

If you _are_ interested I am happy to help redesign the architecture
